// <auto-generated />
using System;
using DotNet.Dbcontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotNet.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotNet.Table.BusTable", b =>
                {
                    b.Property<string>("BusId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BusSeatCount")
                        .HasColumnType("integer");

                    b.Property<string>("BusType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Bus");
                });

            modelBuilder.Entity("DotNet.Table.SeatTable", b =>
                {
                    b.Property<string>("BusId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeatId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeatPlace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeatPrice")
                        .HasColumnType("integer");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Seat");
                });

            modelBuilder.Entity("Table.CustomerTable", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("DateJoined");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CustomerEmail");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("CustomerId");

                    b.Property<string>("LoginPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LoginPassword");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CustomerMobileNo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CustomerName");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
